
/*
 * This file was automatically generated by sdbuscpp-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__perftest_proxy_h__proxy__H__
#define __sdbuscpp__perftest_proxy_h__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace sdbuscpp {

class perftest_proxy
{
public:
    static constexpr const char* interfaceName = "org.sdbuscpp.perftest";

protected:
    perftest_proxy(sdbus::IObjectProxy& object)
        : object_(object)
    {
        object_.uponSignal("dataSignal").onInterface(interfaceName).call([this](const std::string& data){ this->onDataSignal(data); });
    }

    virtual void onDataSignal(const std::string& data) = 0;

public:
    void sendDataSignals(const uint32_t& numberOfSignals, const uint32_t& signalMsgSize)
    {
        object_.callMethod("sendDataSignals").onInterface(interfaceName).withArguments(numberOfSignals, signalMsgSize);
    }

    std::string concatenateTwoStrings(const std::string& string1, const std::string& string2)
    {
        std::string result;
        object_.callMethod("concatenateTwoStrings").onInterface(interfaceName).withArguments(string1, string2).storeResultsTo(result);
        return result;
    }

private:
    sdbus::IObjectProxy& object_;
};

}} // namespaces

#endif
